/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ZombieFactory } from "./ZombieFactory";
export * as factories from "./factories";
export { ZombieFactory__factory } from "./factories/ZombieFactory__factory";
